kind = "mobile"
previewPath = "/"
title = "wahatna"
version = "1.0.0"
id = "artifacts/wahatna-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19246

[services.development]
run = "pnpm --filter @workspace/wahatna-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wahatna-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wahatna-mobile", "run", "serve" ]

[services.env]
PORT = "19246"
BASE_PATH = "/"
